name: ci
on:
  push:
  create:
    tags:
      - v*

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Report
        env:
          GH_GIST_TOKEN: ${{ secrets.GH_GIST_TOKEN }}
        run: |
          export CI_SERVICE_NAME="github-actions"
          bash <(curl -s https://raw.githubusercontent.com/cidverse/cienvsamples/main/scripts/report.sh)
